#!/bin/bash
# Generic flexmem wrapper

#Linux: sharedobject
#	export LD_PRELOAD=flexmem.so
#Mac: sharedobject
#	export DYLD_INSERT_LIBRARIES="flexmem.so"

if test $# -lt 1; then
  echo "Usage:"
  echo "flexmem <program> [[arg1], [arg2], ...]"
  exit 1
fi

# Allow users to define FLEXMEM_HOME
if test -z "${FLEXMEM_HOME}"; then
  FLEXMEM_HOME=
fi
FLEXMEM=${FLEXMEM_HOME}/lib/libflexmem.so

# Acquire the path of flexmem script
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ];
do
  SOURCE="$(readlink "$SOURCE")" [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Check existence of library, if not found make a weak attempt at finding it
# before bailing out.
if test ! -f "${FLEXMEM}"; then
  FLEXMEM=$(find ${DIR}/../ -name "libflexmem.so")
fi
if test ! -f "${FLEXMEM}" -o -z "${FLEXMEM}"; then
  echo "Can't find libflexmem.so, consider setting FLEXMEM_HOME"
  exit 1
fi

# Run whatever
export LD_PRELOAD=${FLEXMEM}
exec "$@"
